name: C/C++ CI

on: [push]

jobs:
  build: A Parking Lot System

    runs-on:
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
